### ISSUE TITLE
Running the contributed command: 'phpunit.Test' failed.

### ISSUE THREAD

**Issue by jimmy4o4** [santigarcor/vscode-phpunit-extended#9]
Hello,

Since vscode (windows 10 x64) updated to version 1.40, and now with version 1.40.1 every PHPUnit command from your extension stopped working. Some of them, but not all, emit notification with message: "Running the contributed command: 'phpunit.Test' failed."

In developer tools console error details are printed:

> notificationsAlerts.ts:38 Error: Running the contributed command: 'phpunit.Test' failed.
    at v._executeContributedCommand (d:\PATH_TO_APPDATA\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:527:959)
    at v.$executeContributedCommand (d:\PATH_TO_APPDATA\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:528:217)
    at f._doInvokeHandler (d:\PATH_TO_APPDATA\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:646:285)
    at f._invokeHandler (d:\PATH_TO_APPDATA\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:645:999)
    at f._receiveRequest (d:\PATH_TO_APPDATA\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:644:664)
    at f._receiveOneMessage (d:\PATH_TO_APPDATA\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:643:477)
    at d:\PATH_TO_APPDATA\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:641:754
    at l.fire (d:\PATH_TO_APPDATA\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
    at _.fire (d:\PATH_TO_APPDATA\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:187:274)
    at d:\PATH_TO_APPDATA\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:798:104
    at l.fire (d:\PATH_TO_APPDATA\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
    at _.fire (d:\PATH_TO_APPDATA\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:187:274)
    at t.PersistentProtocol._receiveMessage (d:\PATH_TO_APPDATA\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:191:629)
    at d:\PATH_TO_APPDATA\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:188:824
    at l.fire (d:\PATH_TO_APPDATA\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:47:207)
    at f.acceptChunk (d:\PATH_TO_APPDATA\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:184:737)
    at d:\PATH_TO_APPDATA\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:184:89
    at Socket.t (d:\PATH_TO_APPDATA\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:193:68)
    at Socket.emit (events.js:200:13)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)

My workspace config looks like this and it  has not changed recently:
```json
"phpunit.execPath": ".\\bin\\phpunit.bat",
"phpunit.args": [
	"--no-coverage"
],
```

Please, help.

**Comment by jimmy4o4** [comment]
After vscode update to version 1.40.2 everything is back to normal.
